name: New Version

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        id: vars
        shell: bash
        run: |
          VERSION=${{ inputs.version }}
          echo "Setting version: $VERSION"
          sed -i "s/^version=.*/version=$VERSION/" gradle.properties
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          git commit -a -m "Releasing version $VERSION"
          git push origin main