name: Current Version

on:
  workflow_call:

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: vars
        shell: bash
        run: |
          VERSION=$(awk -F'=' '/^version=/ {print $2}' gradle.properties)
          echo "Detected version: $VERSION"
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT