name: New Version

on:
  workflow_call:

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION=${{ github.event.inputs.version }}
          sed -i '' "s/^version=.*/version=$VERSION/" gradle.properties
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          git commit -a -m "Releasing version $VERSION"
          git push origin main