name: Build

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      JAVA_VERSION:
        required: true
        type: string
      JAVA_DISTRO:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Version
        run: |
          VERSION=${{ inputs.VERSION }}
          echo "Used version: $VERSION"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.JAVA_DISTRO }}
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Gradle
        id: Build
        run: ./gradlew -q --no-daemon --scan build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ !cancelled() && env.SONAR_TOKEN != '' }}
        run: ./gradlew sonar -Dsonar.gradle.skipCompile=true