name: Java CI with Gradle

on:
  push:
    branches: [ feature/core ]
  pull_request:
    branches: [ feature/core ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Javadoc
        run: ./gradlew aggregateJavadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: build/docs/javadoc

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco
          path: build/reports/jacoco/testCodeCoverageReport/html